### ISSUE TITLE
Save the IP address

### ISSUE THREAD

**Issue by fduraibi** [The1andONLYdave/fireinstaller#1]
Currently whenever i start the app i have to put in my fire stick IP address, it would be great if the app saves the last used IP since it mostly the same.

**Comment by The1andONLYdave** [comment]
Do you have the old Version 0.7 which is also in master-tree?
You could try the current build from develop-tree, 0.8.12 free, which should save your ip in preferences and has also some more features lile a dialog for processing. Its the .apk with vanilla, the donateVersion isnt very stable at the moment.

**Comment by The1andONLYdave** [comment]
You can download it from Google Play or https://github.com/The1andONLYdave/fireinstaller/blob/develop/app/app-vanilla-release.apk

**Comment by fduraibi** [comment]
I was using the one from google play and thought this is the code for it. So there is no plan on making the current version open source?

**Comment by The1andONLYdave** [comment]
The current version is still open souce, but some versions had stability issues, so its only in develop-branch for now.

**Comment by fduraibi** [comment]
:+1:

**Comment by The1andONLYdave** [comment]
Closed: Current Version saves last used IP in Preferences.
:)
